"""
Closed-loop, real-time validation engine.

This directly answers the mentor's challenge — "how will you validate
your idea in real time?" — by implementing the loop the spec calls for:

  PREDICT -> (simulated) EVENT -> VALIDATE -> METRICS

Because the prototype has no access to a live banking/transaction feed,
outcomes are generated by a controlled simulation (never real data, never
real money) rather than pretended to be real-time. The simulation can be
steered towards specific scenarios so the demo can show both hits and
misses honestly, matching the test cases in the problem statement
(strong prediction, top-K success, geographic near miss, complete miss).
"""

import math
import random
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import List, Optional

import pandas as pd

from ml.case_predictor import LocationPrediction

SCENARIOS = [
    "Realistic (data-driven)",
    "Strong Prediction (Top-1 Hit)",
    "Top-3 Success (not #1)",
    "Geographic Near Miss",
    "Complete Miss",
]


@dataclass
class SimulatedEvent:
    location: str
    latitude: float
    longitude: float
    lead_minutes: int
    actual_time: datetime


@dataclass
class ValidationResult:
    top1_hit: bool
    topk_hit: bool
    geo_error_km: float
    time_window_hit: bool
    lead_minutes: int
    actual_location: str
    actual_time: datetime
    low_confidence: bool


def haversine_km(lat1, lon1, lat2, lon2) -> float:
    R = 6371.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dlambda / 2) ** 2
    return 2 * R * math.asin(math.sqrt(a))


def _minutes_until_hour(target_hour: int, rng: random.Random) -> int:
    """Minutes from now until the next occurrence of target_hour (jittered
    within that hour), so simulated events land at realistic clock times
    instead of being an arbitrary random offset from 'now'."""
    now = datetime.now()
    candidate = now.replace(hour=target_hour % 24, minute=rng.randint(0, 59), second=0, microsecond=0)
    if candidate <= now:
        candidate += timedelta(days=1)
    return max(1, int((candidate - now).total_seconds() // 60))


def simulate_event(
    predictions: List[LocationPrediction],
    candidates: pd.DataFrame,
    scenario: str,
    rng: Optional[random.Random] = None,
) -> SimulatedEvent:
    """Generate a synthetic withdrawal event for a set of predictions.

    `candidates` must be the full set of withdrawal locations for the
    case's city (same table `case_predictor` scored against), with
    columns: withdrawal_location, latitude, longitude, risk_score,
    peak_risk_hour.

    The event's simulated clock time is anchored to the *actual chosen
    location's* historical peak withdrawal hour (with jitter) rather than
    an arbitrary offset from wall-clock time, so time-window accuracy is
    a meaningful signal rather than coincidence.
    """
    rng = rng or random

    top1 = predictions[0]
    top_locations = {p.location for p in predictions}

    def peak_hour_for(loc_code: str, fallback: int) -> int:
        match = candidates[candidates["withdrawal_location"] == loc_code]
        if not match.empty and int(match.iloc[0]["peak_risk_hour"]) >= 0:
            return int(match.iloc[0]["peak_risk_hour"])
        return fallback

    if scenario == "Strong Prediction (Top-1 Hit)":
        chosen_loc, lat, lon = top1.location, top1.latitude, top1.longitude
        target_hour = top1.peak_risk_hour

    elif scenario == "Top-3 Success (not #1)" and len(predictions) > 1:
        pick = rng.choice(predictions[1:])
        chosen_loc, lat, lon = pick.location, pick.latitude, pick.longitude
        target_hour = pick.peak_risk_hour

    elif scenario in ("Geographic Near Miss", "Complete Miss"):
        others = candidates[~candidates["withdrawal_location"].isin(top_locations)].copy()
        if others.empty:
            chosen_loc, lat, lon = top1.location, top1.latitude, top1.longitude
            target_hour = top1.peak_risk_hour
        else:
            others["dist_km"] = others.apply(
                lambda r: haversine_km(top1.latitude, top1.longitude, r["latitude"], r["longitude"]),
                axis=1,
            )
            others = others.sort_values("dist_km", ascending=(scenario == "Geographic Near Miss"))
            chosen = others.iloc[0]
            chosen_loc, lat, lon = chosen["withdrawal_location"], chosen["latitude"], chosen["longitude"]
            target_hour = peak_hour_for(chosen_loc, top1.peak_risk_hour)

    else:  # Realistic (data-driven): weighted random sample by true risk score
        weights = candidates["risk_score"].clip(lower=1.0)
        chosen = candidates.sample(1, weights=weights, random_state=rng.randint(0, 10_000)).iloc[0]
        chosen_loc, lat, lon = chosen["withdrawal_location"], chosen["latitude"], chosen["longitude"]
        target_hour = peak_hour_for(chosen_loc, top1.peak_risk_hour)

    # small jitter so it's not always exactly on the peak hour
    target_hour = (target_hour + rng.choice([-1, 0, 0, 1])) % 24
    lead_minutes = _minutes_until_hour(target_hour, rng)
    actual_time = datetime.now() + timedelta(minutes=lead_minutes)

    return SimulatedEvent(
        location=chosen_loc, latitude=float(lat), longitude=float(lon),
        lead_minutes=lead_minutes, actual_time=actual_time,
    )


def validate(
    predictions: List[LocationPrediction],
    event: SimulatedEvent,
    low_confidence_threshold: float = 45.0,
) -> ValidationResult:
    top1 = predictions[0]
    top1_hit = event.location == top1.location
    topk_hit = event.location in {p.location for p in predictions}
    geo_error_km = haversine_km(top1.latitude, top1.longitude, event.latitude, event.longitude)

    actual_hour = event.actual_time.hour
    ws, we = top1.window_start, top1.window_end
    if ws <= we:
        time_hit = ws <= actual_hour <= we
    else:
        time_hit = actual_hour >= ws or actual_hour <= we

    return ValidationResult(
        top1_hit=top1_hit,
        topk_hit=topk_hit,
        geo_error_km=round(geo_error_km, 2),
        time_window_hit=time_hit,
        lead_minutes=event.lead_minutes,
        actual_location=event.location,
        actual_time=event.actual_time,
        low_confidence=top1.confidence < low_confidence_threshold,
    )


def summarize_history(history: List[dict]) -> dict:
    """history: list of dicts each containing a 'validation': ValidationResult"""
    if not history:
        return {
            "count": 0, "top1_accuracy": None, "topk_accuracy": None,
            "avg_geo_error_km": None, "time_window_accuracy": None,
            "avg_lead_minutes": None,
        }
    n = len(history)
    top1_hits = sum(1 for h in history if h["validation"].top1_hit)
    topk_hits = sum(1 for h in history if h["validation"].topk_hit)
    time_hits = sum(1 for h in history if h["validation"].time_window_hit)
    avg_geo = sum(h["validation"].geo_error_km for h in history) / n
    avg_lead = sum(h["validation"].lead_minutes for h in history) / n

    return {
        "count": n,
        "top1_accuracy": top1_hits / n * 100,
        "topk_accuracy": topk_hits / n * 100,
        "avg_geo_error_km": avg_geo,
        "time_window_accuracy": time_hits / n * 100,
        "avg_lead_minutes": avg_lead,
    }
